const GAME = {
  title: "Guardianes",
  subtitle: "Bienestar financiero",
  course: "6° Básico",

  stations: [
    {
      id: 1,
      code: "01",
      slug: "fraudes",
      title: "El detective anti-estafas",
      short: "Fraudes",
      emoji: "🔎",
      color: "#E24B4A",
      keyLabel: "Palabra",
      intro:
        "Revisa 8 mensajes. Sepáralos en ALERTA (parece un engaño) y NORMAL. Anota por qué te parecieron sospechosos los de alerta.",
      talk: "¿Has recibido alguna vez un mensaje parecido a alguno de estos? ¿Qué harías ahora, después de esta actividad?",
      feedback:
        "Las 4 alertas reales eran las tarjetas 1, 2, 4 y 6: todas pedían una contraseña o datos personales, o generaban apuro para que actuaras sin pensar. Las normales (3, 5, 7 y 8) venían de un contacto conocido y no pedían nada extraño. Para dudar de un mensaje, pregúntate: ¿me pide una clave o datos? ¿me apura a decidir ya? ¿es de alguien que realmente conozco?",
    },
    {
      id: 2,
      code: "02",
      slug: "consumo",
      title: "Antes de comprar, comparar",
      short: "Consumo",
      emoji: "👟",
      color: "#E8873A",
      keyLabel: "Dígito",
      intro:
        "Tomás quiere zapatillas de $30.000. Ya tiene $20.000. Le faltan $10.000. Su mesada es de $5.000 a la semana. Calcula las 3 opciones y elige la más conveniente.",
      talk: "¿Alguna vez tuviste que elegir entre comprar algo ahora o esperar a juntar la plata? ¿Qué elegiste y por qué?",
      feedback:
        "La opción más conveniente era la B: ahorrar dos mesadas. No cuesta nada extra y esperas lo mismo que en la A. La A parece más rápida, pero termina costando $3.000 de más — eso es lo que significa «pedir prestado con interés». La C tampoco cuesta extra, solo toma más tiempo (5 semanas), así que también es válida si de verdad no puedes esperar 2 semanas.",
    },
    {
      id: 3,
      code: "03",
      slug: "ahorro",
      title: "¿Qué haces con un regalo?",
      short: "Ahorro",
      emoji: "🐷",
      color: "#2A9D8F",
      keyLabel: "Código %",
      intro:
        "Recibiste $10.000 de cumpleaños. Elige 3 fichas de porcentaje (sin repetir) que sumen 100% para Ahorrar, Gastar y Compartir. El ahorro debe ser igual o mayor que el gasto.",
      talk: "¿Alguna vez ahorraste para algo que realmente querías? ¿Cómo te fue?",
      feedback:
        "No existe una única combinación correcta: lo importante es que el porcentaje de ahorro sea igual o mayor al de gasto. Por ejemplo, 40% ahorro / 30% gasto / 30% compartir funciona porque guardas más de lo que gastas, y además compartes algo.",
    },
    {
      id: 4,
      code: "04",
      slug: "cuidar",
      title: "Cada riesgo, su protección",
      short: "Cuidar",
      emoji: "🛡",
      color: "#5B6BC0",
      keyLabel: "Palabra",
      intro:
        "Hay 6 riesgos y 6 protecciones. Arma las 6 parejas: cada riesgo con su protección correcta. Por cada acierto desbloqueas una letra.",
      talk: "¿Cuál de estos riesgos te ha pasado a ti o a alguien que conoces? ¿Cómo lo resolvieron?",
      feedback:
        "Hay dos formas de cuidar algo: prevenir (como el kit de la bici o la funda del celular, que evitan que el problema pase) y estar cubierto (como el seguro de salud o de hogar, que te ayuda cuando el problema ya pasó). Las dos son importantes y se complementan.",
    },
    {
      id: 5,
      code: "05",
      slug: "crecer",
      title: "Guardar no es lo mismo que crecer",
      short: "Crecer",
      emoji: "📈",
      color: "#C9A227",
      keyLabel: "Dígito",
      intro:
        "Compara los dos chanchitos y calcula la diferencia. Luego lee la oferta y marca las señales de alerta.",
      talk: "¿Por qué la cuenta de ahorro entrega más dinero que guardar el dinero en un cajón? ¿Qué ventaja tiene ahorrar en una institución financiera?",
      feedback:
        "El Chanchito B terminó con $2.500 más sin hacer nada extra, solo por tener su plata en una cuenta que paga intereses: el dinero «trabaja» con el tiempo. Guardar en un cajón mantiene la plata segura, pero no la hace crecer. Y la oferta del «Grupo Ahorro Rápido» tenía las 4 señales de alerta juntas: eso la delata como estafa.",
    },
  ],

  cards: [
    {
      id: 1,
      kind: "sms",
      from: "+56 9 8123 4567",
      handle: "Desconocido",
      body: "¡FELICIDADES! 🎉 Fuiste seleccionado para ganar un iPhone 15 PRO GRATIS. Reclama tu premio aquí antes que se acabe 👉 bit.ly/premio-2026",
      alert: true,
      hint: "Premio no pedido, urgencia y un link acortado.",
    },
    {
      id: 2,
      kind: "roblox",
      from: "soporte.roblox_ok",
      handle: "Soporte",
      body: "Hola! Detectamos actividad sospechosa en tu cuenta. Envíanos tu usuario y contraseña para verificarla o será bloqueada en 24 hrs ⚠",
      alert: true,
      hint: "Pide contraseña y amenaza con bloquearte.",
    },
    {
      id: 3,
      kind: "whatsapp",
      from: "Mamá",
      handle: "💛 Mamá",
      body: "Hijo, no olvides tu colación, quedó en el mesón. Te paso a buscar a las 17:30 😘",
      alert: false,
      hint: "Contacto conocido, sin pedir datos ni dinero.",
    },
    {
      id: 4,
      kind: "game",
      from: "Free Fire",
      handle: "🎮 Free Fire",
      body: "Pro_Gamer2024 te escribió:\n«Oye! te regalo 500 diamantes GRATIS si me pasas tu usuario y clave para activarlo 😉»",
      alert: true,
      hint: "Un desconocido pide usuario y clave.",
    },
    {
      id: 5,
      kind: "school",
      from: "Colegio Los Andes",
      handle: "🏫 Colegio",
      body: "Se suspenden las clases de Ed. Física de mañana por lluvia. Los alumnos deben traer ropa de cambio igual.",
      alert: false,
      hint: "Aviso escolar habitual, sin pedir nada.",
    },
    {
      id: 6,
      kind: "email",
      from: "netflix-verificacion.cl",
      handle: "✉ Correo",
      body: "⚠ Tu cuenta Netflix será cancelada en 2 horas.\nVerifica tus datos bancarios AHORA para no perder el acceso a tu cuenta familiar: netflix-verificacion.cl/confirmar",
      alert: true,
      hint: "Pide datos bancarios con amenaza de tiempo. El correo no es de Netflix.",
    },
    {
      id: 7,
      kind: "whatsapp",
      from: "Fran (curso)",
      handle: "F Fran",
      body: "Hola! te paso el link del grupo del curso para el trabajo de Historia: chat.whatsapp.com/grupo6B 📚",
      alert: false,
      hint: "Compañero conocido y un contexto esperado.",
    },
    {
      id: 8,
      kind: "whatsapp",
      from: "Papá",
      handle: "👨 Papá",
      body: "¿Puedes comprar pan camino a la casa? Te dejé la plata justa sobre la mesa del comedor.",
      alert: false,
      hint: "Contacto conocido, no pide clave ni datos.",
    },
  ],

  options: [
    {
      id: "A",
      title: "Préstamo del compañero",
      text: "Un compañero le presta los $10.000 hoy, pero le pide que le devuelva $13.000 en dos semanas.",
      extra: 3000,
      weeks: 2,
    },
    {
      id: "B",
      title: "Ahorrar las mesadas",
      text: "Ahorra sus próximas 2 mesadas completas (2 semanas) hasta juntar los $10.000 exactos.",
      extra: 0,
      weeks: 2,
    },
    {
      id: "C",
      title: "Préstamo de papá",
      text: "Su papá le presta $10.000 sin cobrarle nada extra, pero debe devolver $2.000 de su mesada cada semana, por 5 semanas.",
      extra: 0,
      weeks: 5,
    },
  ],

  chips: [10, 20, 30, 40, 50],
  gift: 10000,

  pairs: [
    {
      id: "R1",
      letter: "S",
      risk: "Se te pincha la rueda de la bici en el camino al colegio.",
      riskIcon: "🚲",
      prot: "Revisar la bici antes de salir y andar con un kit básico de reparación.",
      protIcon: "🔧",
    },
    {
      id: "R2",
      letter: "E",
      risk: "Se te cae y se quiebra la pantalla del celular.",
      riskIcon: "📱",
      prot: "Usar una funda protectora y no prestarlo a cualquiera.",
      protIcon: "🛡",
    },
    {
      id: "R3",
      letter: "G",
      risk: "Te enfermas y debes ir a una clínica.",
      riskIcon: "🤒",
      prot: "El seguro de salud o escolar cubre parte del costo de la atención.",
      protIcon: "🏥",
    },
    {
      id: "R4",
      letter: "U",
      risk: "Pierdes tu mochila en el paseo de curso.",
      riskIcon: "🎒",
      prot: "Marcar tus cosas con tu nombre y avisar rápido si algo se pierde.",
      protIcon: "🏷",
    },
    {
      id: "R5",
      letter: "R",
      risk: "Se moja tu cuaderno porque se te olvidó la funda para la lluvia.",
      riskIcon: "🌧",
      prot: "Llevar los útiles en una funda o bolsa impermeable.",
      protIcon: "📦",
    },
    {
      id: "R6",
      letter: "O",
      risk: "Sin querer, rompes un vidrio jugando en la casa de un amigo.",
      riskIcon: "🏠",
      prot: "El seguro de hogar de la familia cubre reparaciones como esa.",
      protIcon: "📄",
    },
  ],

  signals: [
    "Promete ganar mucho más de lo normal",
    "Apura a decidir rápido",
    "Pide guardar el secreto",
    "No explica de dónde sale la plata extra",
  ],

  keys: {
    1: "DUDA",
    2: "7",
    4: "SEGURO",
    5: "6",
  },
};
